//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrearsAssignment
    {
        public ArrearsAssignment()
        {
            this.SalaryArrears = new HashSet<SalaryArrear>();
        }
    
        public int arrearAssignID { get; set; }
        public int arrearsElement { get; set; }
        public Nullable<int> payItemId { get; set; }
        public Nullable<decimal> percentVariance { get; set; }
        public Nullable<decimal> scalarValue { get; set; }
        public Nullable<int> startPeriod { get; set; }
        public Nullable<int> endPeriod { get; set; }
        public string arrearScope { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public System.DateTime dateUpdated { get; set; }
        public string whoUpdated { get; set; }
        public string LogRefID { get; set; }
    
        public virtual ListItem ListItem { get; set; }
        public virtual PayItem PayItem { get; set; }
        public virtual ICollection<SalaryArrear> SalaryArrears { get; set; }
    }
}
