//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetID { get; set; }
        public string BudgetCode { get; set; }
        public string FinancialYear { get; set; }
        public Nullable<int> MdaID { get; set; }
        public Nullable<int> TotalApprovedStaff { get; set; }
        public Nullable<decimal> TotalApprovedBudgetSalary { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
        public string LogRefID { get; set; }
    
        public virtual MdaGovernmentMapping MdaGovernmentMapping { get; set; }
    }
}
