//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectorateListing
    {
        public DirectorateListing()
        {
            this.TransferredEmployees = new HashSet<TransferredEmployee>();
        }
    
        public int directorateID { get; set; }
        public Nullable<int> financeDirectorateID { get; set; }
        public string directorateCode { get; set; }
        public string directorateName { get; set; }
        public int mdaID { get; set; }
        public string directorateLocation { get; set; }
        public Nullable<int> directorateType { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
    
        public virtual MdaGovernmentMapping MdaGovernmentMapping { get; set; }
        public virtual ICollection<TransferredEmployee> TransferredEmployees { get; set; }
    }
}
