//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeePayItems = new HashSet<EmployeePayItem>();
            this.SystemUsers = new HashSet<SystemUser>();
            this.TransferredEmployees = new HashSet<TransferredEmployee>();
            this.EmployeeBankAccounts = new HashSet<EmployeeBankAccount>();
        }
    
        public long EmployeeID { get; set; }
        public string prefix { get; set; }
        public string surName { get; set; }
        public string givenName { get; set; }
        public string otherNames { get; set; }
        public string gender { get; set; }
        public System.DateTime dateofBirth { get; set; }
        public Nullable<int> maritalStatus { get; set; }
        public string EmployeePIN { get; set; }
        public string NationalID { get; set; }
        public string Nationality { get; set; }
        public string hrmisCode { get; set; }
        public System.DateTime dateofAppointment { get; set; }
        public bool IsActive { get; set; }
        public string email { get; set; }
        public string phoneMobile { get; set; }
        public string phoneMobile2 { get; set; }
        public string phoneMobile3 { get; set; }
        public Nullable<int> home_StateID { get; set; }
        public string address { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoCreated { get; set; }
        public string whoUpdated { get; set; }
        public string LogRefID { get; set; }
        public Nullable<System.DateTime> lastPromotionDate { get; set; }
        public Nullable<System.DateTime> lastIncrementDate { get; set; }
    
        public virtual EmployeeAssignment EmployeeAssignment { get; set; }
        public virtual ICollection<EmployeePayItem> EmployeePayItems { get; set; }
        public virtual EmployeePayroll EmployeePayroll { get; set; }
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
        public virtual ICollection<TransferredEmployee> TransferredEmployees { get; set; }
        public virtual ICollection<EmployeeBankAccount> EmployeeBankAccounts { get; set; }
    }
}
