//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAssignmentEvidence
    {
        public int EmployeeEvidenceID { get; set; }
        public long EmployeeID { get; set; }
        public int evidenceReferenceNo { get; set; }
        public string evidenceSignedBy { get; set; }
        public System.DateTime evidenceSignedOn { get; set; }
        public string evidenceComment { get; set; }
        public string filecontentType { get; set; }
        public string fileoriginalName { get; set; }
        public byte[] fileContent { get; set; }
        public Nullable<int> fileSize { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoCreated { get; set; }
        public string whoUpdated { get; set; }
        public string LogRefID { get; set; }
    }
}
