//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEvent
    {
        public int employeeEventID { get; set; }
        public long EmployeeID { get; set; }
        public int EventID { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public string EventDescription { get; set; }
        public int EffectOnSalary { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<int> StartPeriod { get; set; }
        public Nullable<int> EndPeriod { get; set; }
        public bool status { get; set; }
        public Nullable<int> payItemID { get; set; }
        public string jobKey { get; set; }
        public Nullable<int> ActingGrade { get; set; }
        public string authorizedBy { get; set; }
        public System.DateTime authorizedOn { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
        public string LogRefID { get; set; }
    
        public virtual EmployeeAssignment EmployeeAssignment { get; set; }
        public virtual PayItem PayItem { get; set; }
    }
}
