//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Government
    {
        public Government()
        {
            this.Government1 = new HashSet<Government>();
            this.MdaGovernmentMappings = new HashSet<MdaGovernmentMapping>();
        }
    
        public int governmentID { get; set; }
        public string governmentCode { get; set; }
        public string governmentName { get; set; }
        public int governmentLevelID { get; set; }
        public int linkToID { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
        public byte[] GovernmentLogo { get; set; }
    
        public virtual ICollection<Government> Government1 { get; set; }
        public virtual Government Government2 { get; set; }
        public virtual ICollection<MdaGovernmentMapping> MdaGovernmentMappings { get; set; }
    }
}
