//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationConfig
    {
        public int installationId { get; set; }
        public string installation_key { get; set; }
        public string installation_value { get; set; }
        public string installation_token { get; set; }
        public int mdaId { get; set; }
        public string whoCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoUpdated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
    
        public virtual MdaGovernmentMapping MdaGovernmentMapping { get; set; }
    }
}
