//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListType
    {
        public ListType()
        {
            this.ListItems = new HashSet<ListItem>();
        }
    
        public int listtypeID { get; set; }
        public string listTypeText { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoCreated { get; set; }
        public string whoUpdated { get; set; }
    
        public virtual ICollection<ListItem> ListItems { get; set; }
    }
}
