//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public ListItem()
        {
            this.ArrearsAssignments = new HashSet<ArrearsAssignment>();
        }
    
        public int listID { get; set; }
        public int listTypeID { get; set; }
        public string listText { get; set; }
        public int listValue { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoCreated { get; set; }
        public string whoUpdated { get; set; }
    
        public virtual ICollection<ArrearsAssignment> ArrearsAssignments { get; set; }
        public virtual ListType ListType { get; set; }
    }
}
