//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDA_CONFIG
    {
        public int MDA_CONFIG_ID { get; set; }
        public int MDAID { get; set; }
        public string CONFIG_KEY { get; set; }
        public string CONFIG_VALUE { get; set; }
    
        public virtual MdaGovernmentMapping MdaGovernmentMapping { get; set; }
    }
}
