//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdaStructure
    {
        public MdaStructure()
        {
            this.MdaGovernmentMappings = new HashSet<MdaGovernmentMapping>();
            this.PayItemMDAStructureMappings = new HashSet<PayItemMDAStructureMapping>();
        }
    
        public int mdaStructureID { get; set; }
        public string mdaStructureName { get; set; }
        public Nullable<int> mdaStructureType { get; set; }
        public Nullable<int> sectorID { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
    
        public virtual ICollection<MdaGovernmentMapping> MdaGovernmentMappings { get; set; }
        public virtual ICollection<PayItemMDAStructureMapping> PayItemMDAStructureMappings { get; set; }
    }
}
