//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayItem
    {
        public PayItem()
        {
            this.EmployeeEvents = new HashSet<EmployeeEvent>();
            this.EmployeePayItems = new HashSet<EmployeePayItem>();
            this.PayItemMDAStructureMappings = new HashSet<PayItemMDAStructureMapping>();
        }
    
        public int payItemID { get; set; }
        public string chartofAccountCode { get; set; }
        public Nullable<int> payItemOrder { get; set; }
        public string payItemCode { get; set; }
        public string payItemName { get; set; }
        public string payItemDescription { get; set; }
        public string payItemType { get; set; }
        public bool IsComputed { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsRecurring { get; set; }
        public bool IsPensionable { get; set; }
        public bool IsTaxable { get; set; }
        public bool IsMandatory { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
        public string LogRefID { get; set; }
    
        public virtual ICollection<EmployeeEvent> EmployeeEvents { get; set; }
        public virtual ICollection<EmployeePayItem> EmployeePayItems { get; set; }
        public virtual ICollection<PayItemMDAStructureMapping> PayItemMDAStructureMappings { get; set; }
    }
}
