//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayItemGradeMapping
    {
        public int PayScaleID { get; set; }
        public int PayItemID { get; set; }
        public int PayGradeID { get; set; }
        public int IncrementPoint { get; set; }
        public decimal PayItemAmount { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
    
        public virtual PayItem PayItem { get; set; }
        public virtual PayScale PayScale { get; set; }
    }
}
