//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE_CONFIG
    {
        public int SITE_CONFIG_ID { get; set; }
        public string CONFIG_KEY { get; set; }
        public string CONFIG_VALUE { get; set; }
    }
}
