//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public SystemUser()
        {
            this.SystemUserMdas = new HashSet<SystemUserMda>();
            this.SystemUserRoles = new HashSet<SystemUserRole>();
            this.SystemUserSupervisedMdas = new HashSet<SystemUserSupervisedMda>();
        }
    
        public int SystemUserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Surname { get; set; }
        public string GivenName { get; set; }
        public string OtherNames { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public bool Active { get; set; }
        public bool Locked { get; set; }
        public string LastIpAddress { get; set; }
        public int UserLoginCount { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string WhoCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string WhoModified { get; set; }
        public string LogRefId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<SystemUserMda> SystemUserMdas { get; set; }
        public virtual ICollection<SystemUserRole> SystemUserRoles { get; set; }
        public virtual ICollection<SystemUserSupervisedMda> SystemUserSupervisedMdas { get; set; }
    }
}
