//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRole
    {
        public SystemRole()
        {
            this.SystemRolePermissions = new HashSet<SystemRolePermission>();
            this.SystemUserRoles = new HashSet<SystemUserRole>();
        }
    
        public int SystemRoleId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string SystemName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string WhoCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string WhoModified { get; set; }
    
        public virtual ICollection<SystemRolePermission> SystemRolePermissions { get; set; }
        public virtual ICollection<SystemUserRole> SystemUserRoles { get; set; }
    }
}
