//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferredEmployee
    {
        public int TransferredEmployeeId { get; set; }
        public long EmployeeID { get; set; }
        public string TransferReason { get; set; }
        public bool IsPermanent { get; set; }
        public string TransferXML { get; set; }
        public string TransferDirection { get; set; }
        public Nullable<int> FromDirectorateId { get; set; }
        public Nullable<int> FromGrade { get; set; }
        public Nullable<int> ToGrade { get; set; }
        public Nullable<int> ToMDAID { get; set; }
        public string AuthorizedBy { get; set; }
        public System.DateTime AuthorizedOn { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MdaGovernmentMapping MdaGovernmentMapping { get; set; }
        public virtual DirectorateListing DirectorateListing { get; set; }
    }
}
