//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransData
    {
        public long RowGuid { get; set; }
        public string ActionType { get; set; }
        public string TableName { get; set; }
        public System.DateTime TransDate { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public long EmployeeID { get; set; }
        public string LogRefID { get; set; }
        public int SyncPeriod { get; set; }
        public string Username { get; set; }
        public int MdaId { get; set; }
        public int state { get; set; }
    }
}
