//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferredEmployee
    {
        public long EmployeeID { get; set; }
        public string TransferReason { get; set; }
        public string TransferXML { get; set; }
        public string TransferDirection { get; set; }
        public int FromDirectorateId { get; set; }
        public int FromGrade { get; set; }
        public int StartPeriodDestination { get; set; }
        public int TransferState { get; set; }
        public int ToGrade { get; set; }
        public int ToMDAID { get; set; }
        public int FromMDAID { get; set; }
        public string AuthorizedBy { get; set; }
        public System.DateTime AuthorizedOn { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
    }
}
