//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHTPayrollHistoryTemp
    {
        public int payrollPeriod { get; set; }
        public int governmentID { get; set; }
        public int mdaID { get; set; }
        public int directorateID { get; set; }
        public System.DateTime payrollDate { get; set; }
        public string payItemsXMLDIR { get; set; }
        public string payItemsXMLMDA { get; set; }
        public string payItemsXMLGOV { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string whoCreated { get; set; }
    }
}
