//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsepsII.Synchronisation.Services.SyncServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sseps.org/", ConfigurationName="SyncServiceReference.SynchronizationWebServiceSoap")]
    public interface SynchronizationWebServiceSoap {
        
        // CODEGEN: Generating message contract since message AuthenticateUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://sseps.org/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserResponse AuthenticateUser(SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sseps.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserResponse> AuthenticateUserAsync(SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since message ReceiveSyncTransaDataObjectsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://sseps.org/ReceiveSyncTransaDataObjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsResponse ReceiveSyncTransaDataObjects(SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sseps.org/ReceiveSyncTransaDataObjects", ReplyAction="*")]
        System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsResponse> ReceiveSyncTransaDataObjectsAsync(SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsRequest request);
        
        // CODEGEN: Generating message contract since message SendApprovedDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://sseps.org/SendApprovedData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataResponse SendApprovedData(SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sseps.org/SendApprovedData", ReplyAction="*")]
        System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataResponse> SendApprovedDataAsync(SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sseps.org/")]
    public partial class SecuredWebServiceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string siteIDField;
        
        private string installationTokenField;
        
        private string authenticatedTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InstallationToken {
            get {
                return this.installationTokenField;
            }
            set {
                this.installationTokenField = value;
                this.RaisePropertyChanged("InstallationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthenticatedToken {
            get {
                return this.authenticatedTokenField;
            }
            set {
                this.authenticatedTokenField = value;
                this.RaisePropertyChanged("AuthenticatedToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://sseps.org/", IsWrapped=true)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sseps.org/")]
        public SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://sseps.org/", IsWrapped=true)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sseps.org/", Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveSyncTransaDataObjects", WrapperNamespace="http://sseps.org/", IsWrapped=true)]
    public partial class ReceiveSyncTransaDataObjectsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sseps.org/")]
        public SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sseps.org/", Order=0)]
        public string syncXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sseps.org/", Order=1)]
        public int siteId;
        
        public ReceiveSyncTransaDataObjectsRequest() {
        }
        
        public ReceiveSyncTransaDataObjectsRequest(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, string syncXml, int siteId) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.syncXml = syncXml;
            this.siteId = siteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveSyncTransaDataObjectsResponse", WrapperNamespace="http://sseps.org/", IsWrapped=true)]
    public partial class ReceiveSyncTransaDataObjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sseps.org/", Order=0)]
        public string ReceiveSyncTransaDataObjectsResult;
        
        public ReceiveSyncTransaDataObjectsResponse() {
        }
        
        public ReceiveSyncTransaDataObjectsResponse(string ReceiveSyncTransaDataObjectsResult) {
            this.ReceiveSyncTransaDataObjectsResult = ReceiveSyncTransaDataObjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendApprovedData", WrapperNamespace="http://sseps.org/", IsWrapped=true)]
    public partial class SendApprovedDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sseps.org/")]
        public SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sseps.org/", Order=0)]
        public int siteId;
        
        public SendApprovedDataRequest() {
        }
        
        public SendApprovedDataRequest(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, int siteId) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.siteId = siteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendApprovedDataResponse", WrapperNamespace="http://sseps.org/", IsWrapped=true)]
    public partial class SendApprovedDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sseps.org/", Order=0)]
        public string SendApprovedDataResult;
        
        public SendApprovedDataResponse() {
        }
        
        public SendApprovedDataResponse(string SendApprovedDataResult) {
            this.SendApprovedDataResult = SendApprovedDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SynchronizationWebServiceSoapChannel : SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SynchronizationWebServiceSoapClient : System.ServiceModel.ClientBase<SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap>, SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap {
        
        public SynchronizationWebServiceSoapClient() {
        }
        
        public SynchronizationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SynchronizationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserResponse SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap.AuthenticateUser(SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserRequest inValue = new SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserResponse retVal = ((SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserResponse> SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap.AuthenticateUserAsync(SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserResponse> AuthenticateUserAsync(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader) {
            SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserRequest inValue = new SsepsII.Synchronisation.Services.SyncServiceReference.AuthenticateUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            return ((SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsResponse SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap.ReceiveSyncTransaDataObjects(SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsRequest request) {
            return base.Channel.ReceiveSyncTransaDataObjects(request);
        }
        
        public string ReceiveSyncTransaDataObjects(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, string syncXml, int siteId) {
            SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsRequest inValue = new SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.syncXml = syncXml;
            inValue.siteId = siteId;
            SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsResponse retVal = ((SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap)(this)).ReceiveSyncTransaDataObjects(inValue);
            return retVal.ReceiveSyncTransaDataObjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsResponse> SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap.ReceiveSyncTransaDataObjectsAsync(SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsRequest request) {
            return base.Channel.ReceiveSyncTransaDataObjectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsResponse> ReceiveSyncTransaDataObjectsAsync(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, string syncXml, int siteId) {
            SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsRequest inValue = new SsepsII.Synchronisation.Services.SyncServiceReference.ReceiveSyncTransaDataObjectsRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.syncXml = syncXml;
            inValue.siteId = siteId;
            return ((SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap)(this)).ReceiveSyncTransaDataObjectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataResponse SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap.SendApprovedData(SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataRequest request) {
            return base.Channel.SendApprovedData(request);
        }
        
        public string SendApprovedData(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, int siteId) {
            SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataRequest inValue = new SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.siteId = siteId;
            SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataResponse retVal = ((SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap)(this)).SendApprovedData(inValue);
            return retVal.SendApprovedDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataResponse> SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap.SendApprovedDataAsync(SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataRequest request) {
            return base.Channel.SendApprovedDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataResponse> SendApprovedDataAsync(SsepsII.Synchronisation.Services.SyncServiceReference.SecuredWebServiceHeader SecuredWebServiceHeader, int siteId) {
            SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataRequest inValue = new SsepsII.Synchronisation.Services.SyncServiceReference.SendApprovedDataRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.siteId = siteId;
            return ((SsepsII.Synchronisation.Services.SyncServiceReference.SynchronizationWebServiceSoap)(this)).SendApprovedDataAsync(inValue);
        }
    }
}
